### ISSUE TITLE
can you share the dataset after alignment

### ISSUE THREAD

**Issue by KennyTC** [GuillaumeMougeot/DogFaceNet#5]
![image](https://user-images.githubusercontent.com/16069257/128794766-4ca63257-ed52-430b-bae5-42fc9edc6999.png)

I read your paper and feel really excited because it is near to the problem I am facing with. 

Would you please to share the dataset after preprocessing (the dataset on the right of the image)

**Comment by GuillaumeMougeot** [comment]
Hi,

the entire dataset is now available on [Zenodo](https://zenodo.org/records/12578449)
