### ISSUE TITLE
Where is landmark data?

### ISSUE THREAD

**Issue by Aiden-0209** [GuillaumeMougeot/DogFaceNet#7]
I like your awesome project.

I download the dataset below page.
https://github.com/GuillaumeMougeot/DogFaceNet/releases/

but I can't find landmark data or a pre-train model. 
It is only 244 * 244 images.
Can you share it?

**Comment by GuillaumeMougeot** [comment]
Hi,

the landmark dataset is now available on [Zenodo](https://zenodo.org/records/12578449)
